##################################################################################################################
# Message definition adapted from https://github.com/b-it-bots/mas_perception_msgs/blob/noetic/msg/ObjectView.msg
##################################################################################################################

sensor_msgs/Image image
sensor_msgs/Image mask
sensor_msgs/PointCloud2 point_cloud
